version: "0.0.1.{build}"
branches:
 except:
   - gh-pages
configuration:
  - Debug
  - Release
install:
  - ps: If (($env:CONFIGURATION -imatch "Release")) { choco install -y InnoSetup }
  - git submodule update --init
image: Visual Studio 2017
before_build:
  - nuget restore
build:
  project: buttplug-csharp.sln
skip_commits:
  files:
    - README.md
after_test:
  - ps: If (($env:CONFIGURATION -imatch "Release")) { set PATH=%PATH%;"C:\\Program Files (x86)\\Inno Setup 5" }
  - ps: If (($env:CONFIGURATION -imatch "Release")) { iscc buttplug-installer.iss }
cache:
  - packages -> **\packages.config
