branches:
 except:
   - gh-pages
configuration:
  - Debug
  - Release
image: Visual Studio 2017

# Taken from https://boblokerse.github.io/2015/11/03/GitVersion-versioning-made-easy-and-dry/
install:
  - ver
  - ps: If (($env:CONFIGURATION -imatch "Release")) { choco install -y InnoSetup }
  - git submodule update --init
  - ps: |
      function gitVersion(){
        $gitVersion=git describe --tags --abbrev=0 $env:APPVEYOR_REPO_BRANCH
        
        $newVersion="$gitVersion.$env:APPVEYOR_BUILD_NUMBER"
        $newHash=git rev-parse HEAD
        write-host "Update appveyor build version to:$newVersion"
        $env:appveyor_build_version="$newVersion"
        appveyor UpdateBuild -Version "$newVersion"
      }
      gitVersion

# patch the assembly version
assembly_info:
   patch: true
   file: '**\AssemblyInfo.*'
   assembly_version: '{version}'
   assembly_file_version: '{version}'
   assembly_informational_version: '{newHash}'

before_build:
  - nuget restore
build:
  project: buttplug-csharp.sln
skip_commits:
  files:
    - README.md
test_script:
 - ps: .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:"ButtplugTest\bin\$env:CONFIGURATION\ButtplugTest.dll -noshadow" -output:"coverage.xml"
after_test:
 - ps: If (($env:CONFIGURATION -imatch "Debug")) { "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%" }
 - ps: If (($env:CONFIGURATION -imatch "Debug")) { pip install codecov }
 - ps: If (($env:CONFIGURATION -imatch "Debug")) { codecov -f "coverage.xml" -X gcov }
 - ps: If (($env:CONFIGURATION -imatch "Release")) { set PATH=%PATH%;"C:\\Program Files (x86)\\Inno Setup 5" }
 - ps: If (($env:CONFIGURATION -imatch "Release")) { iscc buttplug-installer.iss }
 - ps: If (($env:CONFIGURATION -imatch "Release")) { Push-AppveyorArtifact installer\buttplug-installer.exe -FileName Buttplug-$env:APPVEYOR_BUILD_VERSION-installer.exe }
cache:
  - packages -> **\packages.config
